### ISSUE TITLE
how to use that?

### ISSUE THREAD

**Issue by whoizit** [arcnmx/mosh-server-upnp#3]
`mosh-server-upnp` should be installed on VPS or on client?

install `mosh-server-upnp` on client and VPS, `mosh-server-upnp` available in PATH on VPS and client over user `user`
launch on client:
```
$ mosh --server=/home/user/.cargo/bin/mosh-server-upnp --ssh='ssh -p 2022' user@46.46.46.46`

mosh-server (mosh 1.3.2) [build mosh-1.3.2]
Copyright 2012 Keith Winstein <mosh-devel@mit.edu>
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

[mosh-server detached, pid = 21628]
mosh-server-upnp error: IO error
Connection to 46.46.46.46 closed.
/usr/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?
```
```
$ mosh --server=mosh-server-upnp --ssh='ssh -p 2022' user@46.46.46.46
bash: mosh-server-upnp: command not found
Connection to 46.46.46.46 closed.
/usr/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)
```
```
$ mosh-server-upnp -h
mosh-server-upnp error: expected connection data
```

**Comment by arcnmx** [comment]
`mosh-server-upnp` only needs to be on the server, you're using it correctly. Though, it sounds strange to have a VPS provider where your server is behind a NAT with a UPnP router?

`mosh-server-upnp error: IO error` unfortunately means that it is failing to communicate with a upnp device to open the port. The existing error reporting/handling code is incomplete and unhelpful - for more details it would need modification. Easiest debug approach is probably to try tcpdump and see what's failing.

**Comment by whoizit** [comment]
there isn't upnp on server side, but udp port is open (tested with netcat). Idk what to do. It's fresh install without firewall rules

**Comment by arcnmx** [comment]
If there isn't UPnP on the server side, then this tool will not help you. mosh alone is already meant to be able to punch a UDP hole through a NAT on the client side, this tool is for use when the NAT is on the server side.
